"""
Source2Toolkit
Copyright (C) 2025-2026 Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl,
AlliedModders LLC. All rights reserved.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License, version 3.0, as published by the
Free Software Foundation.

This program is distributed in the hope that it will be useful, but WITHOUT
ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
details.

You should have received a copy of the GNU General Public License along with
this program. If not, see <http://www.gnu.org/licenses/>.

As a special exception, Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl and
AlliedModders LLC give you permission to link the code of this program
(as well as its derivative works) to "Counter-Strike 2," "Source 2,"
"Steam," and any Game MODs or server software running on software by
Valve Corporation. You must obey the GNU General Public License in all
respects for all other code used.

Additionally, this exception applies to all derivative works unless
otherwise stated in LICENSE.txt.

Authors:
    - Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl
    - AlliedModders LLC

Project: Source2Toolkit

Public schemagen - generates pure virtual IXxx interface headers (SDK public)
and enum headers.

CXxxImpl.h (core-private implementation wrappers) are generated by
tools/schemagen_core in the core repository.

Reads server.json from schemagen_core (sibling directory in core repo).

Usage:
    python generator.py [sdk_output]

    sdk_output   Base path for SDK public outputs (enums/ and classes/ written here).
                 Default: ../../public/source2toolkit/schema/entity
"""

from __future__ import annotations

import json
import os
import re
import sys
from typing import Optional

# ---------------------------------------------------------------------------
# Import shared schema model from schemagen_core
# ---------------------------------------------------------------------------

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(_SCRIPT_DIR, "../../..", "source2toolkit/tools/", "schemagen_core"))

from generator import (  # noqa: E402
    SchemaTypeCategory,
    SchemaAtomicCategory,
    SchemaFieldType,
    SchemaField,
    SchemaClass,
    SchemaEnum,
    _parse_schema_defs,
    convert_new_schema_to_old,
    build_graph_and_bfs,
    NETWORK_CLASSES,
    EXTRA_WHITELIST,
    HARD_SKIP_CLASSES,
    HARD_SKIP_ENUMS,
    IGNORE_CLASSES,
    IGNORE_CLASS_WILDCARDS,
    contains_ignored_type,
    _field_has_ignored_wildcard,
    sanitise_type_name,
    collect_referenced_types,
    inherits_from_base_entity,
    LICENSE_HEADER,
    make_header_guard,
    write_enum,
    MANUAL_METHODS,
    FIELD_SKIPS,
    to_pascal_case,
    _parse_manual_method,
)

# ---------------------------------------------------------------------------
# Field categorisation helpers
# ---------------------------------------------------------------------------

def _is_pointer_field(field: SchemaField) -> bool:
    return (
        field.type.category == SchemaTypeCategory.FixedArray
        or field.type.name == "CUtlStringToken"
    )


def _virtual_return_type(field: SchemaField) -> str:
    # Globally qualify declared enum/class types to prevent MSVC from confusing
    # the method name with the return type when they share the same identifier
    # (e.g. virtual BloodType& BloodType() would shadow the BloodType type).
    cpp_type = field.type.cpp_type_name
    if field.type.category in (SchemaTypeCategory.DeclaredEnum, SchemaTypeCategory.DeclaredClass):
        cpp_type = f"::{cpp_type}"
    if _is_pointer_field(field):
        return f"{cpp_type}*"
    return f"{cpp_type}&"


# ---------------------------------------------------------------------------
# Effective parent resolution
# ---------------------------------------------------------------------------

def _is_entity_class(class_name: str) -> bool:
    return len(class_name) >= 2 and class_name[0] == "C" and class_name[1].isupper()


def _interface_name(class_name: str) -> str:
    if _is_entity_class(class_name):
        return "I" + class_name[1:]
    return "I" + class_name


def _effective_parent(
    schema_class: SchemaClass,
    generated: set[str],
) -> Optional[str]:
    p = schema_class.parent
    if p is None or p in HARD_SKIP_CLASSES or p not in generated:
        # Special case: CEntityInstance is in HARD_SKIP_CLASSES but we generate IEntityInstance
        if p == "CEntityInstance":
            return "CEntityInstance"
        return None
    if not _is_entity_class(p):
        return None
    return p


# Game SDK headers always included in interface files
_IFACE_SDK_INCLUDES = [
    '#include "igameevents.h"',
    '#include "ehandle.h"',
    '#include "entityhandle.h"',
    '#include "vector.h"',
    '#include "utlsymbol.h"',
    '#include "utlsymbollarge.h"',
    '#include "utlstring.h"',
    '#include "utlstringtoken.h"',
    '#include "source2toolkit/IToolkitTypes.h"',
    '#include "source2toolkit/schema/entityio.h"',
    '#include "source2toolkit/schema/schema.h"',
    "#include <cstdint>",
]

# Extra forward declarations needed in IXxx headers for non-schema types
# referenced by manual methods (types not found in all_classes via substring scan).
_EXTRA_IFACE_FWD_DECLS: dict[str, list[str]] = {
    "CBaseEntity": [
        "CEntityInstance",
        "CEntityIOListenerHandle",
        "CEntitySubclassVDataBase",
        "CEntityKeyValues",
    ],
    "CBasePlayerController": ["CBasePlayerPawn"],
    "CBasePlayerPawn": ["CBasePlayerWeapon"],
    "CBasePlayerWeapon": ["CCSWeaponBaseVData"],
    "CCSGameRules": ["CBasePlayerController", "CCSPlayerController"],
    "CCSPlayerController": ["CCSPlayerPawn", "CCSObserverPawn"],
    "CCSPlayerPawn": ["CCSPlayerController"],
    "CCSPlayer_ItemServices": ["CBasePlayerWeapon"],
    "CCSPlayer_WeaponServices": ["CBasePlayerWeapon"],
    "CPlayerControllerComponent": ["CCSPlayerController"],
    "CPlayerPawnComponent": ["CCSPlayerPawn"],
}

# Extra raw #include lines to inject into IXxx headers for non-schema types.
_EXTRA_IFACE_INCLUDES: dict[str, list[str]] = {
    "CBaseEntity": [
        "#include <functional>",
        '#include "entity2/entitysystem.h"',  # GetEntitySystem() used by FromIndex
    ],
}


# ---------------------------------------------------------------------------
# Manual method virtual declaration helper
# ---------------------------------------------------------------------------

def _manual_method_virtual_decl(m: dict) -> str:
    const = " const" if m["is_const"] else ""
    params = ", ".join(m["params_with_defaults"])
    return f"    virtual {m['return_type']} {m['name']}({params}){const} = 0;"


# ---------------------------------------------------------------------------
# Interface header generation
# ---------------------------------------------------------------------------

def _collect_interface_refs(
    t: SchemaFieldType,
    all_enums: dict[str, SchemaEnum],
    enum_includes: set[str],
    forwards: set[str],
) -> None:
    if t.category == SchemaTypeCategory.DeclaredEnum:
        if t.name not in HARD_SKIP_ENUMS:
            enum_includes.add(t.name)
    elif t.category == SchemaTypeCategory.DeclaredClass:
        if t.name not in HARD_SKIP_CLASSES and '*' not in t.name:
            forwards.add(t.name)
    if t.inner is not None:
        _collect_interface_refs(t.inner, all_enums, enum_includes, forwards)


def write_interface_header(
    class_name: str,
    schema_class: SchemaClass,
    all_enums: dict[str, SchemaEnum],
    all_classes: dict[str, SchemaClass],
    generated: set[str],
) -> str:
    """Generate IFoo.h - a pure virtual interface for class_name."""

    i_class_name = _interface_name(class_name)
    parent = _effective_parent(schema_class, generated)
    i_parent_name = _interface_name(parent) if parent else None

    enum_includes: set[str] = set()
    forwards: set[str] = set()

    # Collect from schema fields
    for f in schema_class.fields:
        if f.type.category == SchemaTypeCategory.Bitfield:
            continue
        if _field_has_ignored_wildcard(f.type):
            continue
        if contains_ignored_type(f.type):
            continue
        _collect_interface_refs(f.type, all_enums, enum_includes, forwards)

    # Collect from manual methods: scan strings for known schema class/enum names
    for method_str in MANUAL_METHODS.get(class_name, []):
        for enum_name in all_enums:
            if enum_name not in HARD_SKIP_ENUMS and enum_name in method_str:
                enum_includes.add(enum_name)
        for cls_name in all_classes:
            if cls_name not in HARD_SKIP_CLASSES and cls_name in method_str:
                forwards.add(cls_name)
        # Forward-declare IXxx interface types referenced in method signatures.
        for m in re.finditer(r'\bI([A-Z][A-Za-z_0-9]*)\b', method_str):
            forwards.add("I" + m.group(1))

    # Extra forward declarations for non-schema types
    for fwd in _EXTRA_IFACE_FWD_DECLS.get(class_name, []):
        forwards.add(fwd)

    forwards.discard(class_name)

    guard = make_header_guard(i_class_name)
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#pragma once",
        "",
    ]

    lines += _IFACE_SDK_INCLUDES

    # Extra includes (e.g. <functional> for std::function)
    extra_incs = _EXTRA_IFACE_INCLUDES.get(class_name, [])
    if extra_incs:
        for inc in extra_incs:
            lines.append(inc)
    lines.append("")

    if i_parent_name:
        if parent == "CEntityInstance":
            lines.append('#include "IEntityInstance.h"')
        else:
            lines.append(f'#include "{i_parent_name}.h"')
        lines.append("")
    else:
        # Root interface classes have no parent that would pull in IEntityInstance.h,
        # but GetOriginal() calls reinterpret_cast<IEntityInstance*>(this)->GetOriginal() — include it explicitly.
        lines.append('#include "IEntityInstance.h"')
        lines.append("")

    for e in sorted(enum_includes):
        lines.append(f'#include "../enums/{sanitise_type_name(e)}.h"')
    if enum_includes:
        lines.append("")

    # Forward-declare the underlying CXxx class for GetOriginal()
    forwards.add(class_name)

    for fwd in sorted(forwards):
        lines.append(f"class {fwd};")
    if forwards:
        lines.append("")

    if i_parent_name:
        lines.append(f"class {i_class_name} : public virtual {i_parent_name}")
    else:
        lines.append(f"class {i_class_name}")

    lines += [
        "{",
        "public:",
        f"    virtual ~{i_class_name}() = default;",
    ]
    # Root classes (no IEntityInstance in hierarchy) declare GetOriginal() as a pure virtual.
    # Child classes inherit it from IEntityInstance — the impl overrides it with the
    # covariant CXxx* return type where both types are complete, so no declaration needed here.
    if not i_parent_name:
        lines.append(f"    virtual {class_name}* GetOriginal() const = 0;")
    lines.append("")

    # Schema field pure virtuals
    _skips = FIELD_SKIPS.get(class_name, set())
    for f in schema_class.fields:
        if f.name in _skips:
            continue
        if f.type.category == SchemaTypeCategory.Bitfield:
            continue
        if _field_has_ignored_wildcard(f.type):
            continue
        if contains_ignored_type(f.type):
            continue

        method_name = to_pascal_case(f.name)
        ret = _virtual_return_type(f)
        lines.append(f"    virtual {ret} {method_name}() = 0;")
        if not _is_pointer_field(f):
            lines.append(f"    virtual void {method_name}Updated() = 0;")

    # Process MANUAL_METHODS: pair each doc comment with the method that follows it.
    # - Instance methods (parseable) -> emit as pure virtuals with their doc comment above.
    # - Static / template methods  -> pass through verbatim with their doc comment above.
    # - Trailing / orphan comments -> pass through as-is.
    virtual_block: list[str] = []
    static_block:  list[str] = []
    pending_comment: Optional[str] = None

    for entry in MANUAL_METHODS.get(class_name, []):
        stripped = entry.strip()
        if stripped.startswith("///"):
            pending_comment = entry
            continue

        is_static_or_template = (
            stripped.startswith("static ") or stripped.startswith("template")
        )

        if is_static_or_template:
            if pending_comment is not None:
                static_block.append(f"    {pending_comment}")
                pending_comment = None
            static_block.append(f"    {entry}")
        else:
            parsed = _parse_manual_method(entry)
            if parsed is not None:
                if pending_comment is not None:
                    virtual_block.append(f"    {pending_comment}")
                    pending_comment = None
                virtual_block.append(_manual_method_virtual_decl(parsed))
            else:
                # Inline-body instance method or unparseable — skip.
                pending_comment = None

    if pending_comment is not None:
        static_block.append(f"    {pending_comment}")

    if virtual_block:
        lines.append("")
        lines += virtual_block

    if static_block:
        lines.append("")
        lines += static_block

    # FromOriginal – static factory; declaration only (defined in CXxx.cpp).
    lines.append(f"    static {i_class_name}* FromOriginal({class_name}* p);")

    lines.append("};")
    lines.append("")
    lines.append(f"#endif // {guard}")
    lines.append("")
    return LICENSE_HEADER + "\r\n".join(lines)


# ---------------------------------------------------------------------------
# IEntityInstance – hard-coded from HL2SDK CEntityInstance vtable
# ---------------------------------------------------------------------------

# Virtual methods extracted verbatim from entity2/entityinstance.h,
# with CEntityInstance* self-references replaced by IEntityInstance*.
_IENTITYINSTANCE_METHODS = [
    "    virtual CNetworkSerializerClassInfo* GetNetworkSerializerInfo() = 0;",
    "    virtual void unk001() = 0;",
    "    virtual void unk002() = 0;",
    "    virtual void* GetScriptDesc() = 0;",
    "    virtual void Connect() = 0;",
    "    virtual void Disconnect() = 0;",
    "    virtual void Precache( const CEntityPrecacheContext* pContext ) = 0;",
    "    virtual void AddedToEntityDatabase() = 0;",
    "    virtual void Spawn( const CEntityKeyValues* pKeyValues ) = 0;",
    "    virtual void unk101() = 0;",
    "    virtual void PostDataUpdate( int updateType ) = 0;",
    "    virtual void OnDataUnchangedInPVS() = 0;",
    "    virtual void Activate( int activateType ) = 0;",
    "    virtual void UpdateOnRemove() = 0;",
    "    virtual void OnSetDormant( int prevDormancyType, int newDormancyType ) = 0;",
    "    virtual void* ScriptEntityIO() = 0;",
    "    virtual int ScriptAcceptInput( const CUtlSymbolLarge& sInputName, IEntityInstance* pActivator, IEntityInstance* pCaller, const variant_t& value, int nOutputID, void* pUnk1, void* pUnk2 ) = 0;",
    "    virtual void PreDataUpdate( int updateType ) = 0;",
    "    virtual void DrawEntityDebugOverlays( uint64_t debug_bits ) = 0;",
    "    virtual void DrawDebugTextOverlays( void* unk, uint64_t debug_bits, int flags ) = 0;",
    "    virtual int Save( ISave& save ) = 0;",
    "    virtual int Restore( IRestore& restore ) = 0;",
    "    virtual void OnSave() = 0;",
    "    virtual void OnRestore() = 0;",
    "    virtual void unk201() = 0;",
    "    virtual int ObjectCaps() = 0;",
    "    virtual CEntityIndex RequiredEdictIndex() = 0;",
    "    virtual void NetworkStateChanged( const NetworkStateChangedData& data ) = 0;",
    "    virtual void unk301( const void* data ) = 0;",
    "    virtual void unk302( const void* data ) = 0;",
    "    virtual void NetworkUpdateState( bool state ) = 0;",
    "    virtual void NetworkStateChangedLog( const char* pszFieldName, const char* pszInfo ) = 0;",
    "    virtual bool FullEdictChanged() = 0;",
    "    virtual void unk401() = 0;",
    "    virtual void unk402() = 0;",
    "    virtual ChangeAccessorFieldPathIndex_t AddChangeAccessorPath( const CFieldPath& path ) = 0;",
    "    virtual void AssignChangeAccessorPathIds() = 0;",
    "    virtual ChangeAccessorFieldPathIndexInfo_t* GetChangeAccessorPathInfo_1() = 0;",
    "    virtual ChangeAccessorFieldPathIndexInfo_t* GetChangeAccessorPathInfo_2() = 0;",
    "    virtual void unk501() = 0;",
    "    virtual void unk502() = 0;",
    "    virtual void ReloadPrivateScripts() = 0;",
    "    virtual datamap_t* GetDataDescMap() = 0;",
    "    virtual void unk601() = 0;",
    "    virtual void unk602() = 0;",
    "    virtual SchemaMetaInfoHandle_t<CSchemaClassInfo> Schema_DynamicBinding() = 0;",
]


def write_ientityinstance_header() -> str:
    guard = make_header_guard("IEntityInstance")
    lines = [
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        "#pragma once",
        "",
    ]
    lines += _IFACE_SDK_INCLUDES
    lines += [
        '#include "entity2/entityinstance.h"',
        '#include "entity2/entitysystem.h"',
        "",
    ]
    lines += [
        "class CEntityInstance;",
        "",
        "class IEntityInstance",
        "{",
        "public:",
        "    virtual ~IEntityInstance() = default;",
        "    virtual CEntityInstance* GetOriginal() const = 0;",
        "",
    ]
    lines += _IENTITYINSTANCE_METHODS
    lines += [
        "",
        "public:",
        "    /// <summary>Create entity by classname.</summary>",
        "    template<typename T>",
        "    static T* New(const char* pszClassName)",
        "    {",
        "        return reinterpret_cast<T*>(_CreateRaw(pszClassName));",
        "    }",
        "    /// <summary>Get entity by index.</summary>",
        "    template<typename T>",
        "    static T* FromIndex(int iIndex)",
        "    {",
        "        return reinterpret_cast<T*>(GetEntitySystem()->GetEntityInstance(CEntityIndex(iIndex)));",
        "    }",
        "    /// <summary>Get entity by entity index.</summary>",
        "    template<typename T>",
        "    static T* FromIndex(CEntityIndex index)",
        "    {",
        "        return FromIndex<T>(index.Get());",
        "    }",
        "    /// <summary>Wrap a raw CEntityInstance pointer as its interface.</summary>",
        "    static IEntityInstance* FromOriginal(CEntityInstance* p);",
        "",
        "private:",
        "    static CEntityInstance* _CreateRaw(const char* pszClassName);",
        "",
        "};",
        "",
        f"#endif // {guard}",
        "",
    ]
    return LICENSE_HEADER + "\r\n".join(lines)


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    script_dir = _SCRIPT_DIR

    # Outputs:
    #   IXxx.h  -> public/source2toolkit/schema/entity/classes/  (SDK public interfaces)
    #   enums/  -> public/source2toolkit/schema/entity/enums/     (SDK public enums)
    # CXxx.h and CXxxImpl.h are generated by tools/schemagen_core in the core repo.
    sdk_output = sys.argv[1] if len(sys.argv) > 1 else os.path.join(
        script_dir, "../../public/source2toolkit/schema/entity"
    )

    schema_path = os.path.join(script_dir, "../../../source2toolkit/tools/schemagen_core/server.json")
    with open(schema_path, encoding="utf-8") as fh:
        raw = json.load(fh)

    defs = _parse_schema_defs(raw["defs"])
    enums, classes = convert_new_schema_to_old(defs)

    all_enums: dict[str, SchemaEnum] = {
        k: v for k, v in sorted(enums.items()) if k not in IGNORE_CLASSES
    }
    all_classes: dict[str, SchemaClass] = {
        k: v for k, v in sorted(classes.items()) if k not in IGNORE_CLASSES
    }

    visited = build_graph_and_bfs(all_classes)
    visited |= EXTRA_WHITELIST

    def should_generate(name: str) -> bool:
        if name in HARD_SKIP_CLASSES:
            return False
        if name not in visited and "VData" not in name:
            return False
        return True

    generated: set[str] = {
        n for n in all_classes if should_generate(n) and _is_entity_class(n)
    }

    sdk_ifaces_dir = os.path.join(sdk_output, "classes")
    sdk_enums_dir  = os.path.join(sdk_output, "enums")

    for out_dir in (sdk_ifaces_dir, sdk_enums_dir):
        if os.path.isdir(out_dir):
            for fname in os.listdir(out_dir):
                if fname.endswith(".h"):
                    os.remove(os.path.join(out_dir, fname))
        os.makedirs(out_dir, exist_ok=True)

    # Enum headers
    for enum_name, schema_enum in all_enums.items():
        if enum_name in HARD_SKIP_ENUMS:
            continue
        content = write_enum(enum_name, schema_enum)
        out_file = os.path.join(sdk_enums_dir, f"{sanitise_type_name(enum_name)}.h")
        with open(out_file, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)

    # IEntityInstance – hard-coded from HL2SDK CEntityInstance vtable
    ientity_path = os.path.join(sdk_ifaces_dir, "IEntityInstance.h")
    with open(ientity_path, "w", encoding="utf-8", newline="") as fh:
        fh.write(write_ientityinstance_header())

    sdk_written = 0

    for class_name, schema_class in all_classes.items():
        if not should_generate(class_name):
            continue
        if not _is_entity_class(class_name):
            continue

        i_name = _interface_name(class_name)
        content = write_interface_header(
            class_name, schema_class, all_enums, all_classes, generated
        )
        out_file = os.path.join(sdk_ifaces_dir, f"{sanitise_type_name(i_name)}.h")
        with open(out_file, "w", encoding="utf-8", newline="") as fh:
            fh.write(content)
        sdk_written += 1

    print(
        f"Done.\n"
        f"  Enums      ({len(all_enums)}): {sdk_enums_dir}\n"
        f"  Interfaces ({sdk_written}): {sdk_ifaces_dir}"
    )


if __name__ == "__main__":
    main()
