#pragma once
#include "CBaseEntity.h"
#include "igameevents.h"
#include "ehandle.h"
#include "entityhandle.h"
#include "vector.h"
#include "utlsymbol.h"
#include "utlsymbollarge.h"
#include "utlstring.h"
#include "utlstringtoken.h"
#include "source2toolkit/IToolkitTypes.h"
#include "source2toolkit/schema/entityio.h"
#include "source2toolkit/schema/schema.h"
#include <cstdint>

#include "CPointEntity.h"
#include "../enums/SceneOnPlayerDeath_t.h"

class CBaseEntity;
class CBaseFlex;
class CSceneListManager;

class CSceneEntity : public CPointEntity
{
public:
    DECLARE_SCHEMA_CLASS(CSceneEntity);

    SCHEMA_FIELD(CUtlSymbolLarge, m_iszSceneFile);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget1);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget2);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget3);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget4);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget5);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget6);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget7);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget8);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget1);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget2);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget3);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget4);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget5);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget6);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget7);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget8);
    SCHEMA_FIELD(CUtlSymbolLarge, m_sTargetAttachment);
    SCHEMA_FIELD(bool, m_bIsPlayingBack);
    SCHEMA_FIELD(bool, m_bPaused);
    SCHEMA_FIELD(bool, m_bMultiplayer);
    SCHEMA_FIELD(bool, m_bAutogenerated);
    SCHEMA_FIELD(float, m_flForceClientTime);
    SCHEMA_FIELD(float, m_flCurrentTime);
    SCHEMA_FIELD(float, m_flFrameTime);
    SCHEMA_FIELD(bool, m_bCancelAtNextInterrupt);
    SCHEMA_FIELD(float, m_fPitch);
    SCHEMA_FIELD(bool, m_bAutomated);
    SCHEMA_FIELD(int32_t, m_nAutomatedAction);
    SCHEMA_FIELD(float, m_flAutomationDelay);
    SCHEMA_FIELD(float, m_flAutomationTime);
    SCHEMA_FIELD(int32_t, m_nSpeechPriority);
    SCHEMA_FIELD(bool, m_bPausedViaInput);
    SCHEMA_FIELD(bool, m_bPauseAtNextInterrupt);
    SCHEMA_FIELD(bool, m_bWaitingForActor);
    SCHEMA_FIELD(bool, m_bWaitingForInterrupt);
    SCHEMA_FIELD(bool, m_bInterruptedActorsScenes);
    SCHEMA_FIELD(bool, m_bBreakOnNonIdle);
    SCHEMA_FIELD(bool, m_bSceneFinished);
    SCHEMA_FIELD(CUtlVector<CHandle<CBaseFlex>>, m_hActorList);
    SCHEMA_FIELD(CUtlVector<CHandle<CBaseEntity>>, m_hRemoveActorList);
    SCHEMA_FIELD(uint16_t, m_nSceneStringIndex);
    SCHEMA_FIELD(CEntityIOOutput, m_OnStart);
    SCHEMA_FIELD(CEntityIOOutput, m_OnCompletion);
    SCHEMA_FIELD(CEntityIOOutput, m_OnCanceled);
    SCHEMA_FIELD(CEntityIOOutput, m_OnPaused);
    SCHEMA_FIELD(CEntityIOOutput, m_OnResumed);
    SCHEMA_FIELD(CHandle<CSceneEntity>, m_hInterruptScene);
    SCHEMA_FIELD(int32_t, m_nInterruptCount);
    SCHEMA_FIELD(bool, m_bSceneMissing);
    SCHEMA_FIELD(bool, m_bInterrupted);
    SCHEMA_FIELD(bool, m_bCompletedEarly);
    SCHEMA_FIELD(bool, m_bInterruptSceneFinished);
    SCHEMA_FIELD(bool, m_bRestoring);
    SCHEMA_FIELD(CUtlVector<CHandle<CSceneEntity>>, m_hNotifySceneCompletion);
    SCHEMA_FIELD(CUtlVector<CHandle<CSceneListManager>>, m_hListManagers);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszSoundName);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszSequenceName);
    SCHEMA_FIELD(CHandle<CBaseFlex>, m_hActor);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hActivator);
    SCHEMA_FIELD(int32_t, m_BusyActor);
    SCHEMA_FIELD(SceneOnPlayerDeath_t, m_iPlayerDeathBehavior);

public:
    static CSceneEntity* New(const char* className)
    {
        return CBaseEntity::New<CSceneEntity>(className);
    }

    static CSceneEntity* FromIndex(int iIndex)
    {
        return CBaseEntity::FromIndex<CSceneEntity>(iIndex);
    }

    static CSceneEntity* FromIndex(CEntityIndex index)
    {
        return FromIndex(index.Get());
    }
};
