/**
* vim: set ts=4 sw=4 tw=99 noet:
 * =============================================================================
 * Source2Toolkit
 * Copyright (C) 2025-2026 Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl,
 * AlliedModders LLC. All rights reserved.
 * =============================================================================
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 3.0, as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * As a special exception, Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl and
 * AlliedModders LLC give you permission to link the code of this program
 * (as well as its derivative works) to "Counter-Strike 2," "Source 2,"
 * "Steam," and any Game MODs or server software running on software by
 * Valve Corporation. You must obey the GNU General Public License in all
 * respects for all other code used.
 *
 * Additionally, this exception applies to all derivative works unless
 * otherwise stated in LICENSE.txt.
 *
 * Authors:
 *   - Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl
 *   - AlliedModders LLC
 *
 * Project: Source2Toolkit
 */

#ifndef _INCLUDE_CSCENEENTITY_H
#define _INCLUDE_CSCENEENTITY_H

#pragma once

#include "CBaseEntity.h"
#include "igameevents.h"
#include "ehandle.h"
#include "entityhandle.h"
#include "vector.h"
#include "utlsymbol.h"
#include "utlsymbollarge.h"
#include "utlstring.h"
#include "utlstringtoken.h"
#include "source2toolkit/IToolkitTypes.h"
#include "source2toolkit/schema/entityio.h"
#include "source2toolkit/schema/schema.h"
#include <cstdint>

#include "CPointEntity.h"
#include "../enums/SceneOnPlayerDeath_t.h"

class CBaseEntity;
class CBaseFlex;
class CSceneListManager;

class CSceneEntity : public CPointEntity
{
public:
    DECLARE_SCHEMA_CLASS(CSceneEntity);

    SCHEMA_FIELD(CUtlSymbolLarge, m_iszSceneFile);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget1);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget2);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget3);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget4);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget5);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget6);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget7);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszTarget8);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget1);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget2);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget3);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget4);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget5);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget6);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget7);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hTarget8);
    SCHEMA_FIELD(CUtlSymbolLarge, m_sTargetAttachment);
    SCHEMA_FIELD(bool, m_bIsPlayingBack);
    SCHEMA_FIELD(bool, m_bPaused);
    SCHEMA_FIELD(bool, m_bMultiplayer);
    SCHEMA_FIELD(bool, m_bAutogenerated);
    SCHEMA_FIELD(float, m_flForceClientTime);
    SCHEMA_FIELD(float, m_flCurrentTime);
    SCHEMA_FIELD(float, m_flFrameTime);
    SCHEMA_FIELD(bool, m_bCancelAtNextInterrupt);
    SCHEMA_FIELD(float, m_fPitch);
    SCHEMA_FIELD(bool, m_bAutomated);
    SCHEMA_FIELD(int32_t, m_nAutomatedAction);
    SCHEMA_FIELD(float, m_flAutomationDelay);
    SCHEMA_FIELD(float, m_flAutomationTime);
    SCHEMA_FIELD(int32_t, m_nSpeechPriority);
    SCHEMA_FIELD(bool, m_bPausedViaInput);
    SCHEMA_FIELD(bool, m_bPauseAtNextInterrupt);
    SCHEMA_FIELD(bool, m_bWaitingForActor);
    SCHEMA_FIELD(bool, m_bWaitingForInterrupt);
    SCHEMA_FIELD(bool, m_bInterruptedActorsScenes);
    SCHEMA_FIELD(bool, m_bBreakOnNonIdle);
    SCHEMA_FIELD(bool, m_bSceneFinished);
    SCHEMA_FIELD(CUtlVector<CHandle<CBaseFlex>>, m_hActorList);
    SCHEMA_FIELD(CUtlVector<CHandle<CBaseEntity>>, m_hRemoveActorList);
    SCHEMA_FIELD(uint16_t, m_nSceneStringIndex);
    SCHEMA_FIELD(CEntityIOOutput, m_OnStart);
    SCHEMA_FIELD(CEntityIOOutput, m_OnCompletion);
    SCHEMA_FIELD(CEntityIOOutput, m_OnCanceled);
    SCHEMA_FIELD(CEntityIOOutput, m_OnPaused);
    SCHEMA_FIELD(CEntityIOOutput, m_OnResumed);
    SCHEMA_FIELD(CHandle<CSceneEntity>, m_hInterruptScene);
    SCHEMA_FIELD(int32_t, m_nInterruptCount);
    SCHEMA_FIELD(bool, m_bSceneMissing);
    SCHEMA_FIELD(bool, m_bInterrupted);
    SCHEMA_FIELD(bool, m_bCompletedEarly);
    SCHEMA_FIELD(bool, m_bInterruptSceneFinished);
    SCHEMA_FIELD(bool, m_bRestoring);
    SCHEMA_FIELD(CUtlVector<CHandle<CSceneEntity>>, m_hNotifySceneCompletion);
    SCHEMA_FIELD(CUtlVector<CHandle<CSceneListManager>>, m_hListManagers);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszSoundName);
    SCHEMA_FIELD(CUtlSymbolLarge, m_iszSequenceName);
    SCHEMA_FIELD(CHandle<CBaseFlex>, m_hActor);
    SCHEMA_FIELD(CHandle<CBaseEntity>, m_hActivator);
    SCHEMA_FIELD(int32_t, m_BusyActor);
    SCHEMA_FIELD(SceneOnPlayerDeath_t, m_iPlayerDeathBehavior);

public:
    static CSceneEntity* New(const char* className)
    {
        return CBaseEntity::New<CSceneEntity>(className);
    }

    static CSceneEntity* FromIndex(int iIndex)
    {
        return CBaseEntity::FromIndex<CSceneEntity>(iIndex);
    }

    static CSceneEntity* FromIndex(CEntityIndex index)
    {
        return FromIndex(index.Get());
    }
};

#endif // _INCLUDE_CSCENEENTITY_H
