/**
* vim: set ts=4 sw=4 tw=99 noet:
 * =============================================================================
 * Source2Toolkit
 * Copyright (C) 2025-2026 Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl,
 * AlliedModders LLC. All rights reserved.
 * =============================================================================
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 3.0, as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * As a special exception, Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl and
 * AlliedModders LLC give you permission to link the code of this program
 * (as well as its derivative works) to "Counter-Strike 2," "Source 2,"
 * "Steam," and any Game MODs or server software running on software by
 * Valve Corporation. You must obey the GNU General Public License in all
 * respects for all other code used.
 *
 * Additionally, this exception applies to all derivative works unless
 * otherwise stated in LICENSE.txt.
 *
 * Authors:
 *   - Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl
 *   - AlliedModders LLC
 *
 * Project: Source2Toolkit
 */

#ifndef _INCLUDE_IMAPINFO_H
#define _INCLUDE_IMAPINFO_H

#pragma once

#include "igameevents.h"
#include "ehandle.h"
#include "entityhandle.h"
#include "vector.h"
#include "utlsymbol.h"
#include "utlsymbollarge.h"
#include "utlstring.h"
#include "utlstringtoken.h"
#include "source2toolkit/IToolkitTypes.h"
#include "source2toolkit/schema/entityio.h"
#include "source2toolkit/schema/schema.h"
#include <cstdint>

#include "IPointEntity.h"

class CMapInfo;

class IMapInfo : public virtual IPointEntity
{
public:
    virtual ~IMapInfo() = default;

    virtual int32_t& BuyingStatus() = 0;
    virtual void BuyingStatusUpdated() = 0;
    virtual float& BombRadius() = 0;
    virtual void BombRadiusUpdated() = 0;
    virtual int32_t& PetPopulation() = 0;
    virtual void PetPopulationUpdated() = 0;
    virtual bool& UseNormalSpawnsForDM() = 0;
    virtual void UseNormalSpawnsForDMUpdated() = 0;
    virtual bool& DisableAutoGeneratedDMSpawns() = 0;
    virtual void DisableAutoGeneratedDMSpawnsUpdated() = 0;
    virtual float& BotMaxVisionDistance() = 0;
    virtual void BotMaxVisionDistanceUpdated() = 0;
    virtual int32_t& HostageCount() = 0;
    virtual void HostageCountUpdated() = 0;
    virtual bool& FadePlayerVisibilityFarZ() = 0;
    virtual void FadePlayerVisibilityFarZUpdated() = 0;
    virtual bool& RainTraceToSkyEnabled() = 0;
    virtual void RainTraceToSkyEnabledUpdated() = 0;
    virtual bool& GPUCullSkybox() = 0;
    virtual void GPUCullSkyboxUpdated() = 0;
    virtual float& EnvRainStrength() = 0;
    virtual void EnvRainStrengthUpdated() = 0;
    virtual float& EnvPuddleRippleStrength() = 0;
    virtual void EnvPuddleRippleStrengthUpdated() = 0;
    virtual float& EnvPuddleRippleDirection() = 0;
    virtual void EnvPuddleRippleDirectionUpdated() = 0;
    virtual float& EnvWetnessCoverage() = 0;
    virtual void EnvWetnessCoverageUpdated() = 0;
    virtual float& EnvWetnessDryingAmount() = 0;
    virtual void EnvWetnessDryingAmountUpdated() = 0;
    static IMapInfo* FromOriginal(CMapInfo* p);
};

#endif // _INCLUDE_IMAPINFO_H
