/**
* vim: set ts=4 sw=4 tw=99 noet:
 * =============================================================================
 * Source2Toolkit
 * Copyright (C) 2025-2026 Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl,
 * AlliedModders LLC. All rights reserved.
 * =============================================================================
 *
 * This program is free software; you can redistribute it and/or modify it under
 * the terms of the GNU General Public License, version 3.0, as published by the
 * Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
 * details.
 *
 * You should have received a copy of the GNU General Public License along with
 * this program. If not, see <http://www.gnu.org/licenses/>.
 *
 * As a special exception, Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl and
 * AlliedModders LLC give you permission to link the code of this program
 * (as well as its derivative works) to "Counter-Strike 2," "Source 2,"
 * "Steam," and any Game MODs or server software running on software by
 * Valve Corporation. You must obey the GNU General Public License in all
 * respects for all other code used.
 *
 * Additionally, this exception applies to all derivative works unless
 * otherwise stated in LICENSE.txt.
 *
 * Authors:
 *   - Michal "Slynx (˙·٠● S l y n x ●٠·˙)" Přikryl
 *   - AlliedModders LLC
 *
 * Project: Source2Toolkit
 */

#ifndef _INCLUDE_ISCENEENTITY_H
#define _INCLUDE_ISCENEENTITY_H

#pragma once

#include "igameevents.h"
#include "ehandle.h"
#include "entityhandle.h"
#include "vector.h"
#include "utlsymbol.h"
#include "utlsymbollarge.h"
#include "utlstring.h"
#include "utlstringtoken.h"
#include "source2toolkit/IToolkitTypes.h"
#include "source2toolkit/schema/entityio.h"
#include "source2toolkit/schema/schema.h"
#include <cstdint>

#include "IPointEntity.h"

#include "../enums/SceneOnPlayerDeath_t.h"

class CBaseEntity;
class CBaseModelEntity;
class CSceneEntity;
class CSceneListManager;

class ISceneEntity : public virtual IPointEntity
{
public:
    virtual ~ISceneEntity() = default;

    virtual CUtlSymbolLarge& SceneFile() = 0;
    virtual void SceneFileUpdated() = 0;
    virtual CUtlSymbolLarge& Target1() = 0;
    virtual void Target1Updated() = 0;
    virtual CUtlSymbolLarge& Target2() = 0;
    virtual void Target2Updated() = 0;
    virtual CUtlSymbolLarge& Target3() = 0;
    virtual void Target3Updated() = 0;
    virtual CUtlSymbolLarge& Target4() = 0;
    virtual void Target4Updated() = 0;
    virtual CUtlSymbolLarge& Target5() = 0;
    virtual void Target5Updated() = 0;
    virtual CUtlSymbolLarge& Target6() = 0;
    virtual void Target6Updated() = 0;
    virtual CUtlSymbolLarge& Target7() = 0;
    virtual void Target7Updated() = 0;
    virtual CUtlSymbolLarge& Target8() = 0;
    virtual void Target8Updated() = 0;
    virtual CHandle<CBaseEntity>& LocatorOrigin() = 0;
    virtual void LocatorOriginUpdated() = 0;
    virtual CUtlSymbolLarge& TargetAttachment() = 0;
    virtual void TargetAttachmentUpdated() = 0;
    virtual bool& IsPlayingBack() = 0;
    virtual void IsPlayingBackUpdated() = 0;
    virtual bool& Paused() = 0;
    virtual void PausedUpdated() = 0;
    virtual bool& Multiplayer() = 0;
    virtual void MultiplayerUpdated() = 0;
    virtual bool& Autogenerated() = 0;
    virtual void AutogeneratedUpdated() = 0;
    virtual bool& AllRequirementsComplete() = 0;
    virtual void AllRequirementsCompleteUpdated() = 0;
    virtual float& ForceClientTime() = 0;
    virtual void ForceClientTimeUpdated() = 0;
    virtual float& CurrentTime() = 0;
    virtual void CurrentTimeUpdated() = 0;
    virtual float& FrameTime() = 0;
    virtual void FrameTimeUpdated() = 0;
    virtual bool& CancelAtNextInterrupt() = 0;
    virtual void CancelAtNextInterruptUpdated() = 0;
    virtual float& Pitch() = 0;
    virtual void PitchUpdated() = 0;
    virtual bool& Automated() = 0;
    virtual void AutomatedUpdated() = 0;
    virtual int32_t& AutomatedAction() = 0;
    virtual void AutomatedActionUpdated() = 0;
    virtual float& AutomationDelay() = 0;
    virtual void AutomationDelayUpdated() = 0;
    virtual float& AutomationTime() = 0;
    virtual void AutomationTimeUpdated() = 0;
    virtual int32_t& SpeechPriority() = 0;
    virtual void SpeechPriorityUpdated() = 0;
    virtual bool& PausedViaInput() = 0;
    virtual void PausedViaInputUpdated() = 0;
    virtual bool& PauseAtNextInterrupt() = 0;
    virtual void PauseAtNextInterruptUpdated() = 0;
    virtual bool& WaitingForActor() = 0;
    virtual void WaitingForActorUpdated() = 0;
    virtual bool& WaitingForInterrupt() = 0;
    virtual void WaitingForInterruptUpdated() = 0;
    virtual bool& InterruptedActorsScenes() = 0;
    virtual void InterruptedActorsScenesUpdated() = 0;
    virtual bool& TakeOverNPCBehavior() = 0;
    virtual void TakeOverNPCBehaviorUpdated() = 0;
    virtual bool& BreakOnNonIdle() = 0;
    virtual void BreakOnNonIdleUpdated() = 0;
    virtual bool& SceneFinished() = 0;
    virtual void SceneFinishedUpdated() = 0;
    virtual CUtlVector<CHandle<CBaseModelEntity>>& ActorList() = 0;
    virtual void ActorListUpdated() = 0;
    virtual CUtlVector<CHandle<CBaseEntity>>& RemoveActorList() = 0;
    virtual void RemoveActorListUpdated() = 0;
    virtual uint16_t& SceneStringIndex() = 0;
    virtual void SceneStringIndexUpdated() = 0;
    virtual ::CEntityIOOutput& OnStart() = 0;
    virtual void OnStartUpdated() = 0;
    virtual ::CEntityIOOutput& OnCompletion() = 0;
    virtual void OnCompletionUpdated() = 0;
    virtual ::CEntityIOOutput& OnCanceled() = 0;
    virtual void OnCanceledUpdated() = 0;
    virtual ::CEntityIOOutput& OnPaused() = 0;
    virtual void OnPausedUpdated() = 0;
    virtual ::CEntityIOOutput& OnResumed() = 0;
    virtual void OnResumedUpdated() = 0;
    virtual ::CEntityIOOutput& OnPulseRequirement() = 0;
    virtual void OnPulseRequirementUpdated() = 0;
    virtual CHandle<CSceneEntity>& InterruptScene() = 0;
    virtual void InterruptSceneUpdated() = 0;
    virtual int32_t& InterruptCount() = 0;
    virtual void InterruptCountUpdated() = 0;
    virtual bool& SceneMissing() = 0;
    virtual void SceneMissingUpdated() = 0;
    virtual bool& Interrupted() = 0;
    virtual void InterruptedUpdated() = 0;
    virtual bool& CompletedEarly() = 0;
    virtual void CompletedEarlyUpdated() = 0;
    virtual bool& InterruptSceneFinished() = 0;
    virtual void InterruptSceneFinishedUpdated() = 0;
    virtual bool& Restoring() = 0;
    virtual void RestoringUpdated() = 0;
    virtual CUtlVector<CHandle<CSceneEntity>>& NotifySceneCompletion() = 0;
    virtual void NotifySceneCompletionUpdated() = 0;
    virtual CUtlVector<CHandle<CSceneListManager>>& ListManagers() = 0;
    virtual void ListManagersUpdated() = 0;
    virtual CUtlSymbolLarge& SoundName() = 0;
    virtual void SoundNameUpdated() = 0;
    virtual CUtlSymbolLarge& SequenceName() = 0;
    virtual void SequenceNameUpdated() = 0;
    virtual CHandle<CBaseModelEntity>& Actor() = 0;
    virtual void ActorUpdated() = 0;
    virtual CHandle<CBaseEntity>& Activator() = 0;
    virtual void ActivatorUpdated() = 0;
    virtual int32_t& BusyActor() = 0;
    virtual void BusyActorUpdated() = 0;
    virtual ::SceneOnPlayerDeath_t& PlayerDeathBehavior() = 0;
    virtual void PlayerDeathBehaviorUpdated() = 0;
    static ISceneEntity* FromOriginal(CSceneEntity* p);
    static ISceneEntity* FromRaw(CEntityInstance* p);
};

#endif // _INCLUDE_ISCENEENTITY_H
