#!/usr/bin/env python3
# vim: set ts=4 sw=4 tw=99 et:
"""
Source2Toolkit SDK -- dependency setup.

The SDK compiles against three things it does not carry in git:

  * hl2sdk-cs2          -- the CS2 branch of AlliedModders' hl2sdk
  * Protobufs (csgo/)   -- SteamDatabase's protobuf definitions
  * KHook               -- vendor/khook, a submodule, which has to be the very
                           commit metamod-source was built with or the toolkit
                           core refuses every plugin at load time
  * hl2sdk-manifests    -- vendor/hl2sdk-manifests, a submodule (AMBuild only)

`init` asks, once, where each of the first two comes from: a checkout you
already have (found through the HL2SDKCS2 / CSGO_PROTO environment variable,
or a path you type) or a clone this script makes under vendor/. The answer is
saved in deps.json next to this SDK, and `update` then brings everything up to
date the same way every time: pulls the checkouts, moves KHook to the commit
metamod-source pins, moves the manifests to their latest.

    python tools/deps.py init
    python tools/deps.py init --hl2sdk download --protobufs env
    python tools/deps.py update
    python tools/deps.py status

Nothing here needs more than Python 3 and git.
"""

import argparse
import json
import os
import subprocess
import sys
import urllib.request

SDK_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CONFIG_PATH = os.path.join(SDK_ROOT, 'deps.json')
CMAKE_PATH = os.path.join(SDK_ROOT, 'deps.cmake')
VENDOR = os.path.join(SDK_ROOT, 'vendor')

# What the toolkit core is built against in CI (docker/docker-entrypoint.sh
# of the source2toolkit repo). The defaults, all of them overridable.
DEFAULTS = {
    'hl2sdk': {
        'env': 'HL2SDKCS2',
        'repo': 'https://github.com/alliedmodders/hl2sdk.git',
        'branch': 'cs2',
        'dir': 'hl2sdk-cs2',
        # What has to exist for a path to count as this dependency.
        'probe': os.path.join('public', 'eiface.h'),
    },
    'protobufs': {
        'env': 'CSGO_PROTO',
        'repo': 'https://github.com/SteamDatabase/Protobufs.git',
        'branch': 'master',
        'dir': 'Protobufs',
        # The env var / config path points at the csgo/ folder inside the clone.
        'subdir': 'csgo',
        'probe': 'netmessages.proto',
    },
}

# KHook follows this repository's pin, read from GitHub without cloning it.
KHOOK_TRACK = {
    'repo': 'alliedmodders/metamod-source',
    'branch': 'master',
    'path': 'third_party/khook',
}


# =========================
# Small helpers
# =========================

def say(msg):
    print('[deps] ' + msg)


def die(msg):
    print('[deps] error: ' + msg, file=sys.stderr)
    sys.exit(1)


def git(args, cwd, check=True, capture=False):
    cmd = ['git'] + args
    if capture:
        return subprocess.run(cmd, cwd=cwd, check=check, stdout=subprocess.PIPE,
                              stderr=subprocess.STDOUT, text=True).stdout.strip()
    return subprocess.run(cmd, cwd=cwd, check=check).returncode


def is_git_repo(path):
    return os.path.isdir(path) and git(['rev-parse', '--is-inside-work-tree'], path,
                                       check=False, capture=True) == 'true'


def git_head(path):
    return git(['rev-parse', 'HEAD'], path, check=False, capture=True) if is_git_repo(path) else ''


def git_dirty(path):
    return bool(git(['status', '--porcelain', '--untracked-files=no'], path, check=False, capture=True))


def pull(path, label):
    """Fast-forward pull, only when the branch has an upstream to pull from."""
    upstream = git(['rev-parse', '--abbrev-ref', '--symbolic-full-name', '@{u}'], path, check=False, capture=True)
    if not upstream or upstream.startswith('fatal'):
        say('{}: {} has no upstream branch, not pulling'.format(label, path))
        return
    say('{}: pulling {}'.format(label, path))
    git(['pull', '--ff-only', '--quiet'], path, check=False)
    git(['submodule', 'update', '--init', '--recursive', '--quiet'], path, check=False)


def probe(path, dep):
    return bool(path) and os.path.isfile(os.path.join(path, DEFAULTS[dep]['probe']))


def load_config():
    if not os.path.isfile(CONFIG_PATH):
        return None
    with open(CONFIG_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)


def save_config(config):
    with open(CONFIG_PATH, 'w', encoding='utf-8') as f:
        json.dump(config, f, indent=2)
        f.write('\n')
    write_cmake(config)
    say('saved ' + os.path.relpath(CONFIG_PATH, SDK_ROOT) + ' and ' + os.path.relpath(CMAKE_PATH, SDK_ROOT))


def write_cmake(config):
    """CMake 3.18 cannot read JSON, so the paths go into a file it can include.
    Only the downloaded ones and typed paths: a plain env-var choice is what
    CMake does anyway."""
    lines = ['# Generated by tools/deps.py -- do not edit, run `deps.py init` again.']
    for dep, var in (('hl2sdk', 'SOURCESDK'), ('protobufs', 'PROTOBUFS')):
        entry = config.get(dep, {})
        if entry.get("mode") == "download" or entry.get("path"):
            lines.append('set({} "{}")'.format(var, resolved_path(dep, entry).replace('\\', '/')))
    with open(CMAKE_PATH, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines) + '\n')


def resolved_path(dep, entry):
    """Where the dependency is, for the mode saved."""
    d = DEFAULTS[dep]
    if entry['mode'] == 'env':
        return entry.get('path') or os.environ.get(d['env'], '')
    clone = os.path.join(VENDOR, d['dir'])
    return os.path.join(clone, d['subdir']) if d.get('subdir') else clone


def clone_dir(dep):
    return os.path.join(VENDOR, DEFAULTS[dep]['dir'])


# =========================
# init
# =========================

def ask_choice(dep, env_path):
    d = DEFAULTS[dep]
    print()
    print('{}:'.format(dep))
    if env_path:
        print('  1) use the checkout {} points at: {}'.format(d['env'], env_path))
    else:
        print('  1) use a checkout I already have ({} is not set -- you will be asked for the path)'.format(d['env']))
    print('  2) download {} ({}) into vendor/{}'.format(d['repo'], d['branch'], d['dir']))
    while True:
        answer = input('  choice [1/2]: ').strip()
        if answer == '1':
            return 'env'
        if answer == '2':
            return 'download'


def init(args):
    config = load_config() or {}
    interactive = not (args.hl2sdk and args.protobufs)

    for dep in ('hl2sdk', 'protobufs'):
        d = DEFAULTS[dep]
        env_path = os.environ.get(d['env'], '')
        mode = getattr(args, dep)
        if not mode:
            if not sys.stdin.isatty():
                die('--{} is required when not run from a terminal'.format(dep))
            mode = ask_choice(dep, env_path)

        entry = {'mode': mode}
        if mode == 'env':
            path = env_path
            if dep == "protobufs" and env_path and not probe(path, dep) and probe(os.path.join(env_path, "csgo"), dep):
                path = os.path.join(env_path, "csgo")
            if not probe(path, dep):
                if env_path:
                    say('{} = {} does not look like {} ({} missing)'.format(d['env'], env_path, dep, d['probe']))
                if interactive and sys.stdin.isatty():
                    path = input('  path to your {} checkout: '.format(dep)).strip()
                    if dep == 'protobufs' and probe(os.path.join(path, 'csgo'), dep):
                        path = os.path.join(path, 'csgo')
                if not probe(path, dep):
                    die('no usable {} checkout at "{}"'.format(dep, path))
            # Only remember an explicit path; the env var is read fresh each time.
            if path != env_path:
                entry['path'] = os.path.abspath(path)
        else:
            entry['repo'] = getattr(args, dep + '_repo') or d['repo']
            entry['branch'] = getattr(args, dep + '_branch') or d['branch']
        config[dep] = entry

    config['khook'] = {
        'repo': args.metamod_repo or config.get('khook', {}).get('repo', KHOOK_TRACK['repo']),
        'branch': args.metamod_branch or config.get('khook', {}).get('branch', KHOOK_TRACK['branch']),
    }

    save_config(config)
    update(args, config)


# =========================
# update
# =========================

def update_checkout(dep, entry):
    d = DEFAULTS[dep]
    if entry['mode'] == 'env':
        path = resolved_path(dep, entry)
        if dep == 'protobufs' and path.rstrip('/\\').endswith(d['subdir']):
            path = os.path.dirname(path.rstrip('/\\'))
        if not is_git_repo(path):
            say('{}: {} is not a git checkout, left alone'.format(dep, path))
            return
        if git_dirty(path):
            say('{}: {} has local changes, not pulling'.format(dep, path))
            return
        pull(path, dep)
        return

    path = clone_dir(dep)
    if not os.path.isdir(path):
        os.makedirs(VENDOR, exist_ok=True)
        say('{}: cloning {} ({}) into {}'.format(dep, entry['repo'], entry['branch'], os.path.relpath(path, SDK_ROOT)))
        git(['clone', '--recursive', '--branch', entry['branch'], '--single-branch', entry['repo'], path], SDK_ROOT)
        return

    if git_dirty(path):
        say('{}: {} has local changes, not pulling'.format(dep, os.path.relpath(path, SDK_ROOT)))
        return
    pull(path, dep)


def metamod_khook_sha(track):
    """The commit of third_party/khook in the metamod-source repo, from the
    GitHub contents API -- a submodule entry carries its pinned sha."""
    url = 'https://api.github.com/repos/{}/contents/{}?ref={}'.format(track['repo'], KHOOK_TRACK['path'], track['branch'])
    try:
        with urllib.request.urlopen(urllib.request.Request(url, headers={'User-Agent': 'source2toolkit-sdk-deps'}), timeout=20) as r:
            data = json.load(r)
    except Exception as e:  # noqa: BLE001 -- any failure just means "unknown"
        say('khook: could not read {} ({})'.format(url, e))
        return None
    if data.get('type') != 'submodule':
        say('khook: {} in {} is not a submodule'.format(KHOOK_TRACK['path'], track['repo']))
        return None
    return data.get('sha')


def update_khook(track):
    path = os.path.join(VENDOR, 'khook')
    git(['submodule', 'update', '--init', 'vendor/khook'], SDK_ROOT, check=False)
    if not is_git_repo(path):
        die('vendor/khook is not checked out')

    current = git_head(path)
    wanted = metamod_khook_sha(track)
    if not wanted:
        say('khook: staying on {}'.format(current[:12]))
        return
    if wanted == current:
        say('khook: {} already matches {} {}'.format(current[:12], track['repo'], track['branch']))
        return

    say('khook: {} -> {} (the commit {} {} pins)'.format(current[:12], wanted[:12], track['repo'], track['branch']))
    git(['fetch', '--quiet', 'origin'], path, check=False)
    if git(['cat-file', '-e', wanted + '^{commit}'], path, check=False) != 0:
        git(['fetch', '--quiet', 'origin', wanted], path, check=False)
    git(['checkout', '--quiet', '--detach', wanted], path)
    say('khook: vendor/khook now points elsewhere than this SDK commit; commit the submodule bump if this is the SDK you maintain')


def update_manifests():
    say('manifests: vendor/hl2sdk-manifests -> latest master')
    git(['submodule', 'update', '--init', '--remote', 'vendor/hl2sdk-manifests'], SDK_ROOT, check=False)


def update(args, config=None):
    config = config or load_config()
    if not config:
        die('no deps.json yet -- run `deps.py init` first')

    for dep in ('hl2sdk', 'protobufs'):
        if dep in config:
            update_checkout(dep, config[dep])

    if not getattr(args, 'no_khook', False):
        update_khook(config.get('khook', KHOOK_TRACK))
    if not getattr(args, 'no_manifests', False):
        update_manifests()

    write_cmake(config)
    status(args, config)


# =========================
# status
# =========================

def status(args, config=None):
    config = config or load_config()
    if not config:
        die('no deps.json yet -- run `deps.py init` first')

    print()
    for dep in ('hl2sdk', 'protobufs'):
        entry = config.get(dep)
        if not entry:
            print('  {:<10} not configured'.format(dep))
            continue
        path = resolved_path(dep, entry)
        where = 'from ' + DEFAULTS[dep]['env'] if entry['mode'] == 'env' and 'path' not in entry else entry['mode']
        repo = path
        if dep == 'protobufs' and path.rstrip('/\\').endswith(DEFAULTS[dep]['subdir']):
            repo = os.path.dirname(path.rstrip('/\\'))
        head = git_head(repo)
        ok = 'ok' if probe(path, dep) else 'MISSING ' + DEFAULTS[dep]['probe']
        print('  {:<10} {:<10} {}  [{}] {}'.format(dep, where, path, head[:12] or 'not git', ok))

    khook = git_head(os.path.join(VENDOR, 'khook'))
    track = config.get('khook', KHOOK_TRACK)
    print('  {:<10} {:<10} {}  (tracks {} {})'.format('khook', 'submodule', khook[:12] or 'not checked out', track['repo'], track['branch']))
    manifests = git_head(os.path.join(VENDOR, 'hl2sdk-manifests'))
    print('  {:<10} {:<10} {}'.format('manifests', 'submodule', manifests[:12] or 'not checked out'))

    print()
    for dep in ('hl2sdk', 'protobufs'):
        entry = config.get(dep)
        if entry and entry['mode'] == 'download' and os.environ.get(DEFAULTS[dep]['env']):
            print('  note: {} is set in your environment but deps.json says "download" -- '
                  'CMake and AMBuild use the downloaded copy.'.format(DEFAULTS[dep]['env']))


# =========================
# main
# =========================

def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest='command', required=True)

    p_init = sub.add_parser('init', help='choose where hl2sdk-cs2 and the Protobufs come from, then update')
    for dep in ('hl2sdk', 'protobufs'):
        p_init.add_argument('--' + dep, choices=('env', 'download'),
                            help='"env": the checkout {} points at; "download": clone into vendor/'.format(DEFAULTS[dep]['env']))
        p_init.add_argument('--{}-repo'.format(dep), dest=dep + '_repo', help='clone URL for --{} download'.format(dep))
        p_init.add_argument('--{}-branch'.format(dep), dest=dep + '_branch', help='branch for --{} download'.format(dep))
    p_init.add_argument('--metamod-repo', help='GitHub repo whose KHook pin to follow (default {})'.format(KHOOK_TRACK['repo']))
    p_init.add_argument('--metamod-branch', help='branch of that repo (default {})'.format(KHOOK_TRACK['branch']))
    p_init.add_argument('--no-khook', action='store_true', help='leave vendor/khook where it is')
    p_init.add_argument('--no-manifests', action='store_true', help='leave vendor/hl2sdk-manifests where it is')
    p_init.set_defaults(func=init)

    p_update = sub.add_parser('update', help='bring every dependency up to date the way deps.json says')
    p_update.add_argument('--no-khook', action='store_true', help='leave vendor/khook where it is')
    p_update.add_argument('--no-manifests', action='store_true', help='leave vendor/hl2sdk-manifests where it is')
    p_update.set_defaults(func=update)

    p_status = sub.add_parser('status', help='show what is configured and which commits are checked out')
    p_status.set_defaults(func=status)

    args = parser.parse_args()
    args.func(args)


if __name__ == '__main__':
    main()
